/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { TuanChat } from './TuanChat';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AddPostRequest } from './models/AddPostRequest';
export type { AddRoleRequest } from './models/AddRoleRequest';
export type { AdminAddReq } from './models/AdminAddReq';
export type { AdminRevokeReq } from './models/AdminRevokeReq';
export type { ApiResult } from './models/ApiResult';
export type { ApiResultBoolean } from './models/ApiResultBoolean';
export type { ApiResultCursorPageBaseResponseChatMessageResponse } from './models/ApiResultCursorPageBaseResponseChatMessageResponse';
export type { ApiResultCursorPageBaseResponseFriendApplyResp } from './models/ApiResultCursorPageBaseResponseFriendApplyResp';
export type { ApiResultCursorPageBaseResponseFriendResp } from './models/ApiResultCursorPageBaseResponseFriendResp';
export type { ApiResultCursorPageBaseResponsePost } from './models/ApiResultCursorPageBaseResponsePost';
export type { ApiResultFriendCheckResp } from './models/ApiResultFriendCheckResp';
export type { ApiResultFriendUnreadResp } from './models/ApiResultFriendUnreadResp';
export type { ApiResultFullPostResponse } from './models/ApiResultFullPostResponse';
export type { ApiResultIdRespVO } from './models/ApiResultIdRespVO';
export type { ApiResultListChatMemberResp } from './models/ApiResultListChatMemberResp';
export type { ApiResultListRoleAvatar } from './models/ApiResultListRoleAvatar';
export type { ApiResultListRoomGroup } from './models/ApiResultListRoomGroup';
export type { ApiResultListUserRole } from './models/ApiResultListUserRole';
export type { ApiResultLong } from './models/ApiResultLong';
export type { ApiResultMessage } from './models/ApiResultMessage';
export type { ApiResultObject } from './models/ApiResultObject';
export type { ApiResultOssResp } from './models/ApiResultOssResp';
export type { ApiResultPost } from './models/ApiResultPost';
export type { ApiResultRoleAbilityTable } from './models/ApiResultRoleAbilityTable';
export type { ApiResultRoleAvatar } from './models/ApiResultRoleAvatar';
export type { ApiResultRoomResp } from './models/ApiResultRoomResp';
export type { ApiResultString } from './models/ApiResultString';
export type { ApiResultUserInfoResponse } from './models/ApiResultUserInfoResponse';
export type { ApiResultUserRole } from './models/ApiResultUserRole';
export type { ApiResultVoid } from './models/ApiResultVoid';
export type { ChangeBackgroundReq } from './models/ChangeBackgroundReq';
export type { ChatMemberResp } from './models/ChatMemberResp';
export type { ChatMessageMarkRequest } from './models/ChatMessageMarkRequest';
export type { ChatMessagePageRequest } from './models/ChatMessagePageRequest';
export type { ChatMessageRequest } from './models/ChatMessageRequest';
export type { ChatMessageResponse } from './models/ChatMessageResponse';
export type { CursorPageBaseReq } from './models/CursorPageBaseReq';
export type { CursorPageBaseResponseChatMessageResponse } from './models/CursorPageBaseResponseChatMessageResponse';
export type { CursorPageBaseResponseFriendApplyResp } from './models/CursorPageBaseResponseFriendApplyResp';
export type { CursorPageBaseResponseFriendResp } from './models/CursorPageBaseResponseFriendResp';
export type { CursorPageBaseResponsePost } from './models/CursorPageBaseResponsePost';
export type { FriendApplyReq } from './models/FriendApplyReq';
export type { FriendApplyResp } from './models/FriendApplyResp';
export { FriendApproveReq } from './models/FriendApproveReq';
export type { FriendCheck } from './models/FriendCheck';
export type { FriendCheckReq } from './models/FriendCheckReq';
export type { FriendCheckResp } from './models/FriendCheckResp';
export type { FriendDeleteReq } from './models/FriendDeleteReq';
export type { FriendResp } from './models/FriendResp';
export type { FriendUnreadResp } from './models/FriendUnreadResp';
export type { FullPostResponse } from './models/FullPostResponse';
export type { GroupAddRequest } from './models/GroupAddRequest';
export type { IdRespVO } from './models/IdRespVO';
export type { MemberAddRequest } from './models/MemberAddRequest';
export type { MemberDelRequest } from './models/MemberDelRequest';
export type { MemberRequest } from './models/MemberRequest';
export type { Message } from './models/Message';
export type { MessageExtra } from './models/MessageExtra';
export type { MessageMark } from './models/MessageMark';
export type { OssResp } from './models/OssResp';
export type { Post } from './models/Post';
export type { PostImage } from './models/PostImage';
export type { RoleAbilityTable } from './models/RoleAbilityTable';
export type { RoleAvatar } from './models/RoleAvatar';
export type { RoleAvatarCreateRequest } from './models/RoleAvatarCreateRequest';
export type { RoleAvatarRequest } from './models/RoleAvatarRequest';
export type { RoomGroup } from './models/RoomGroup';
export type { RoomResp } from './models/RoomResp';
export type { UploadUrlReq } from './models/UploadUrlReq';
export type { UserInfoResponse } from './models/UserInfoResponse';
export type { UserLoginRequest } from './models/UserLoginRequest';
export type { UserRegisterRequest } from './models/UserRegisterRequest';
export type { UserRole } from './models/UserRole';

export { AvatarControllerService } from './services/AvatarControllerService';
export { ChatControllerService } from './services/ChatControllerService';
export { CommunityControllerService } from './services/CommunityControllerService';
export { FriendControllerService } from './services/FriendControllerService';
export { OssControllerService } from './services/OssControllerService';
export { RoleControllerService } from './services/RoleControllerService';
export { RoomGroupControllerService } from './services/RoomGroupControllerService';
export { UserControllerService } from './services/UserControllerService';
